name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Run Semantic Release
        id: semantic
        uses: docker://ghcr.io/codfish/semantic-release-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Go
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: 1.15.x
      -
        name: Register version on pkg.go.dev
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          package=$(cat go.mod | grep ^module | awk '{print $2}')
          version=v${{ steps.semantic.outputs.release-version }}
          url=https://proxy.golang.org/${package}/@v/${version}.info
          set -x +e
          curl -i $url
